'use server'
import { z } from 'zod'
import { createClient } from '@supabase/supabase-js'
import { getServerUser } from '@/lib/supabase/server'
import { revalidatePath } from 'next/cache'
const supabase = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.SUPABASE_SERVICE_ROLE_KEY!)
async function getRid() { const { profile } = await getServerUser(); if (!profile?.restaurant_id) throw new Error('Sem restaurante'); return profile.restaurant_id }
export async function createCategory(name: string, sortOrder: number) { const rid = await getRid(); const { error } = await supabase.from('categories').insert({ restaurant_id: rid, name, sort_order: sortOrder }); if (error) return { error: error.message }; revalidatePath('/admin/cardapio'); return { success: true } }
export async function updateCategory(id: string, name: string) { const rid = await getRid(); const { error } = await supabase.from('categories').update({ name }).eq('id', id).eq('restaurant_id', rid); if (error) return { error: error.message }; revalidatePath('/admin/cardapio'); return { success: true } }
export async function deleteCategory(id: string) { const rid = await getRid(); const { count } = await supabase.from('products').select('*', { count: 'exact', head: true }).eq('category_id', id); if (count && count > 0) return { error: 'Remova os produtos desta categoria primeiro.' }; const { error } = await supabase.from('categories').delete().eq('id', id).eq('restaurant_id', rid); if (error) return { error: error.message }; revalidatePath('/admin/cardapio'); return { success: true } }
const productSchema = z.object({ name: z.string().min(1), description: z.string().optional(), price: z.coerce.number().min(0), category_id: z.string().uuid(), active: z.boolean().default(true) })
export type ProductInput = z.infer<typeof productSchema>
export async function createProduct(data: ProductInput) { const rid = await getRid(); const p = productSchema.safeParse(data); if (!p.success) return { error: 'Dados inválidos' }; const { error } = await supabase.from('products').insert({ restaurant_id: rid, category_id: p.data.category_id, name: p.data.name, description: p.data.description, price: Math.round(p.data.price*100), active: p.data.active }); if (error) return { error: error.message }; revalidatePath('/admin/cardapio'); return { success: true } }
export async function updateProduct(id: string, data: ProductInput) { const rid = await getRid(); const p = productSchema.safeParse(data); if (!p.success) return { error: 'Dados inválidos' }; const { error } = await supabase.from('products').update({ category_id: p.data.category_id, name: p.data.name, description: p.data.description, price: Math.round(p.data.price*100), active: p.data.active }).eq('id', id).eq('restaurant_id', rid); if (error) return { error: error.message }; revalidatePath('/admin/cardapio'); return { success: true } }
export async function toggleProduct(id: string, active: boolean) { const rid = await getRid(); const { error } = await supabase.from('products').update({ active }).eq('id', id).eq('restaurant_id', rid); if (error) return { error: error.message }; revalidatePath('/admin/cardapio'); return { success: true } }
export async function deleteProduct(id: string) { const rid = await getRid(); const { error } = await supabase.from('products').delete().eq('id', id).eq('restaurant_id', rid); if (error) return { error: error.message }; revalidatePath('/admin/cardapio'); return { success: true } }
